### ISSUE TITLE
right-prompt command duration math leads to "(standard_in) 1: syntax error"

### ISSUE THREAD

**Issue by liblit** [oh-my-fish/theme-bobthefish#107] opened 2017-09-27 00:40 UTC
The default right-prompt printing function (`fish_right_prompt`) calls a helper function named `__bobthefish_cmd_duration`, which in turn contains several uses of `math`:

``` fish
math -s1 "$CMD_DURATION/1000" | string replace -r '\\.0$' ''
...
math -s1 "$CMD_DURATION/60000" | string replace -r '\\.0$' ''
...
math -s2 "$CMD_DURATION/3600000" | string replace -r '(\\.0)?0$' ''
```

Unfortunately, these `math` calls all fail under fish version 2.3.1, which is the standard offering for Fedora 26. Rather than performing the intended calculation, they instead print `(standard_in) 1: syntax error`. The `-s#` flags seem to be the problem, as can be demonstrated by running similar commands directly:

> % math 5678/1000
> 5

> % math 'scale=1;5678/1000'
> 5.6

> % math -s1 5678/1000
> (standard_in) 1: syntax error

I believe that this problem appeared in d87e9486f8a127f06dd576000c9f1a3eb0be6bd3, which in turn was intended to fix issue #105. This change may indeed have fixed things for newer fish 3.x releases, but under fish 2.3.1 it broke things as described here.

**Comment by bobthecow** [comment] 2017-09-29 14:40
Thank you for reporting this, and I'm sorry about the backwards compatibility break. It should be fixed by 0f2a2d9.

I tested against 2.3.x and 2.4.x `math` and both worked great. I couldn't get 3.x built on my machine right now, so I didn't test against that, but it _should_ work the same as before. @yogan do you mind confirming that this still works correctly for you?

**Comment by yogan** [comment] 2017-09-29 15:54
@bobthecow I just did an `omf update` / `omf reload` to get the most recent version of the theme. It seems to be broken again. My fish version is 2.6.0-592-g039c3c1. I'm not sure about the exact version of the theme. Where does omf put its packages?

**Comment by bobthecow** [comment] 2017-09-29 16:43
Awesome. ❤️ breaking changes that you can’t detect by version number.

**Comment by bobthecow** [comment] 2017-10-02 01:31
Okay. It _should_ be fixed for realsies this time. Let me know if it doesn't work for you!

**Closed** 2017-10-02 01:30 UTC

**Comment by yogan** [comment] 2017-10-02 08:25
Works fine. Thanks for the quick fix!

**Comment by bobthecow** [comment] 2017-10-02 16:40
No problem!

**Comment by dwrz** [comment] 2019-01-11 13:34
I ran into this issue today:

```
fish: Unknown command 'math'
~/.local/share/omf/themes/bobthefish/fish_right_prompt.fish (line 7): 
    math "scale=1;$CMD_DURATION/1000" | string replace -r '\\.0$' ''
    ^
in function “__bobthefish_cmd_duration”
	called on line 47 of file ~/.local/share/omf/themes/bobthefish/fish_right_prompt.fish

in function “fish_right_prompt”
	called on standard input

in command substitution
	called on standard input

```

Is it possible there's been a regression?

**Comment by bobthecow** [comment] 2019-01-11 19:00
probably not. `math` is a builtin in fish, and has been for ages:

http://fishshell.com/docs/current/commands.html#math

what fish version are you running?

**Comment by dwrz** [comment] 2019-01-12 01:00
3.00.

Getting outputs like this now:
```
math: Error: Expression is bogus
'scale=1;7400/1000'
     ^
```

**Comment by bobthecow** [comment] 2019-01-12 06:04
what does `type math` say?

**Comment by dwrz** [comment] 2019-01-12 15:30
`math is a builtin`

My personal machine, on `2.7.1`, doesn't have the `math` output and reports `math is a function with a definition`, followed by the definition.

**Comment by bobthecow** [comment] 2019-01-12 15:34
It changed from a function (wrapping `bc`, which was an undeclared dependency) to a builtin at some point, so it’s not surprising that an older version would have the function. I don’t remember which version changed, though.
