### ISSUE TITLE
Bug in duration display (__bobthefish_pretty_ms)

### ISSUE THREAD

**Issue by efc** [oh-my-fish/theme-bobthefish#184] opened 2019-01-16 15:29 UTC
The right prompt will report a duration of 10s or 100s as 1s because it strips all trailing zeros from any reported number. I don't think this is what was intended. You can test this by simply executing `sleep 10` at a prompt.

The problem seems to be in the replace pattern which makes the decimal point optional (`\\.?`)...

```fish
string replace -r '\\.?0*$' $interval
```
I believe what was intended was to make the decimal point required (remove the `?`), like so...

```fish
string replace -r '\\.0*$' $interval
```
With the change, only trailing zeros immediately after a decimal point are removed. So 10.0s would be reported as 10s, but 10s would also be reported as 10s. Unfortunately, 10.250s would be reported as 10.250s, so this pattern is not perfect. But at least it does not lie!

**Comment by efc** [comment] 2019-01-16 15:39
In fact, I'm not sure what problem the fancy replacement is trying to solve. It seems that the `math -s1` already does the trick, so the replace can be much simpler... `string replace -r '$' $interval` seems to be enough.

**Comment by bobthecow** [comment] 2019-01-16 16:12
I believe the issue is that, in previous versions of Fish, the interval was always a float. So this replace is meant to remove all trailing zeros after the decimal, and remove the decimal if it's no longer necessary.

```
10.000 -> 10
10.250 -> 10.25
``

Unfortunately if it's sometimes returning an integer, simply stripping the trailing zeros won't work :)

**Comment by bobthecow** [comment] 2019-01-16 16:19
Thanks for reporting. I've pushed a fix!

**Closed** 2019-01-16 16:19 UTC
