### ISSUE TITLE
This theme slows down interactive shell

### ISSUE THREAD

**Issue by frol** [oh-my-fish/theme-bobthefish#70] opened 2016-12-25 12:35 UTC
I have been using this theme for quite some time, but a few months ago I noticed that my shell is sluggish when I turn my laptop into power save mode. Any other theme I have tried today doesn't introduce any noticeable slowdown. Backspace operation is the slowest, if I have a 50-character-long line and I press and hold backspace for 3 seconds and release it, the shell will continue deleting characters for 4-5 seconds more, so it can remove the whole line while I wanted to remove just a few words.

System info:

* Arch Linux x64 (Core i7 in power save mode running at 800MHz)
* Fish 2.4.0
* Latest bobthefish

**Comment by bobthecow** [comment] 2016-12-25 16:02
I've never been able to reproduce this, but since Fish 2.4.0 I've seen other reports of it. My (completely uneducated) guess is that it's related to right prompt. Wanna try disabling the right prompt and see if it goes away?

**Comment by frol** [comment] 2016-12-25 22:38
Disabling the right prompt made it twice as faster, but I still notice the lag comparing to other themes.

**Comment by ycardon** [comment] 2017-01-04 22:54
same problem: https://github.com/oh-my-fish/theme-bobthefish/issues/66

**Comment by frol** [comment] 2017-01-12 13:48
Yes, downgrade Fish to 2.3.1 helped.

**Comment by frol** [comment] 2017-01-30 12:06
I have spent this morning trying to find the bottleneck and it seems that there is a regression in fish itself. I have also tried compiling Fish from the latest master branch, but the performance stays poor just ike in 2.4.0.

`strace -f` didn't reveal any differences in syscalls comparing Fish 2.3.1 and Fish 2.4.0.

I have narrowed the drop in performance to `set_color` calls in `__bobthefish_start_segment`: https://github.com/oh-my-fish/theme-bobthefish/blob/master/fish_prompt.fish#L197-L222. Commenting all `set_color` there makes my prompt fast again... Any ideas?

**Comment by bobthecow** [comment] 2017-01-30 19:50
Can you come up with a minimal test case that shows whether this is, in fact, a `set_color` issue? Maybe a script that calls `set_color` a bunch of times and echoes some text, or just echoes the text if you pass a different arg?

**Comment by frol** [comment] 2017-01-30 20:05
I have tried to minimize this to a script, but nothing revealed a difference when I tried running Fish 2.3.1 vs 2.4.0 :(

I don't blame `set_color` itself, but it should introduce some sideeffects since removing those calls speeds the shell noticeably.

**Comment by bobthecow** [comment] 2017-02-01 16:45
Do you mind pulling and checking the latest version? It should be a decent amount faster (though the underlying issue remains).

**Comment by frol** [comment] 2017-02-01 17:56
@bobthecow It is somewhat faster, but still not fast enough. This is how my system behaves using the latest BobTheFish + Fish 2.4.0: https://github.com/fish-shell/fish-shell/issues/3793#issuecomment-276730157

**Comment by ycardon** [comment] 2017-02-01 18:02
@bobthecow same as @frol : seems faster, but not significantly.

I think we'll have to wait for the correction of the performance issue inside fish.
Anyway, I really thank you both for taking care of the issue and pointing it to the fish team ^^

**Comment by bobthecow** [comment] 2017-02-01 18:18
Thanks for checking it out, sorry I couldn't help more :)

**Comment by ycardon** [comment] 2017-02-01 18:44
Well, this is ok after all: this performance issue on fish just made your theme better, saving the world some precious CPU cycles (I'm not kidding: energy-safe design is our common concern)

**Comment by faho** [comment] 2017-02-04 16:26
Can anyone here test https://github.com/fish-shell/fish-shell/pull/3811?

**Comment by bobthecow** [comment] 2017-03-31 16:56
The fix for this has been merged into fish master, but looks like it missed the 2.5.0 release. I'm closing this now, assuming that'll do the trick. Feel free to re-open if any of you have further issue :)

See fish-shell/fish-shell#3793

**Closed by bobthecow** 2017-03-31 16:56 UTC
