### ISSUE TITLE
The status "bang" doesn't show when a command failed and a Python virtualenv is activated

### ISSUE THREAD

**Issue by mandx** [oh-my-fish/theme-bobthefish#5] opened 2015-07-14 16:16 UTC
As long as the virtualenv is deactivated, the "!" works as expected, it shows when something fails, and clears when the next command runs successfully. But as long as the virtualenv is activated, it never shows, regardless of the previous command's exit code.

     ~/tmp  virtualenv-3.4 env/
    Using base prefix '/usr'
    New python executable in env/bin/python3
    Also creating executable in env/bin/python
    Installing setuptools, pip, wheel...done.
     ~/tmp  commandthatfails
    commandthatfails: command not found
     !  ~/tmp  source env/bin/activate.fish
    (env) ◰ ³ env  ~/tmp  commandthatfails
    commandthatfails: command not found
    (env) ◰ ³ env  ~/tmp  deactivate
     ~/tmp  commandthatfails
    commandthatfails: command not found
     !  ~/tmp 

![Here's the screenshot of the same output](https://cloud.githubusercontent.com/assets/535282/8678356/4ee12eb6-2a11-11e5-8928-19c394982223.png). The timestamps at the right side of the screen are omitted for clarity, they are always present.

[The activate.fish script](https://gist.github.com/mandx/1a58bc9cd8ffa4f92ac7) used in this test is generated by the `virtualenv` command.

**Comment by bobthecow** [comment] 2015-07-14 16:27
I haven't used virtualenv, but I'd try two things:

First, set `$VIRTUAL_ENV_DISABLE_PROMPT` to disable the automatic virtualenv prompt. It's an uglier duplicate of the one in bobthefish anyway :)

If that doesn't work, I'd check out [virtualfish](https://github.com/adambrenecki/virtualfish). It wouldn't surprise me if the stock virtualenv were just bad at fish in general, since most things I've tried for other languages are.

**Comment by mandx** [comment] 2015-07-14 21:07
Setting the `VIRTUAL_ENV_DISABLE_PROMPT` environment variable worked.

    set -x VIRTUAL_ENV_DISABLE_PROMPT 1

Thanks!

**Closed** 2015-07-19 23:13 UTC
