### ISSUE TITLE
Git does not show on case insensitive FS

### ISSUE THREAD

**Issue by domoritz** [oh-my-fish/theme-bobthefish#191] opened 2019-02-08 17:18 UTC
Note that even though I am in the same directory, once the git branch does not show the second time. 

<img width="400" alt="screen shot 2019-02-08 at 09 17 14" src="https://user-images.githubusercontent.com/589034/52494267-6c0c5080-2b82-11e9-948e-a67ad0dfa3d9.png">

I am on mac os with case insensitive APFS.

**Comment by bobthecow** [comment] 2019-02-08 17:36
Have you updated to the latest version? This should be fixed by 4ccdd7bdcfd615e991321dbc811be69d3b94f2d7

**Comment by domoritz** [comment] 2019-02-08 19:22
I believe so, yes. 

<img width="580" alt="screen shot 2019-02-08 at 11 22 18" src="https://user-images.githubusercontent.com/589034/52500880-d7aae980-2b93-11e9-9d45-5c54820a262d.png">

**Comment by bobthecow** [comment] 2019-02-08 22:06
oh boo :(

are you using git workdirs by chance?

**Comment by domoritz** [comment] 2019-02-08 22:27
I don't think so.

**Comment by paulbhart** [comment] 2019-02-15 04:05
I might have found the cause (at least in my case).  
I have a directory ~/Development in which my git directory resides
![image](https://user-images.githubusercontent.com/2267531/52832727-c9832e80-30a7-11e9-9d95-b0d95e7ba44b.png)

So then consider the new section of code from the https://github.com/oh-my-fish/theme-bobthefish/commit/4ccdd7bdcfd615e991321dbc811be69d3b94f2d7 

![image](https://user-images.githubusercontent.com/2267531/52832765-f9323680-30a7-11e9-8005-e41e84f3be2e.png)

If you used the first cd command with the lower cased development then the case statement at 134 won't match because you are assuming it is a symlink. (i.e. if the names aren't the same, then must be a symlink) and it returns.  But in fact it is just we are on a case insensitive FS and in this case fish seems to just remember exactly what you typed in to get into the directory, vs the actual name.

Take for instance
![image](https://user-images.githubusercontent.com/2267531/52833073-39de7f80-30a9-11e9-80f6-9319e6b30639.png)

In my case I could fix it by just using the string command to lower the case of $PWD, but that won't work for case sensitive FS.  Seems like this is a known issue https://github.com/fish-shell/fish-shell/issues/5255

**Comment by paulbhart** [comment] 2019-02-15 17:23
what is also "weird" is if I just type fish again, pwd now returns the correct value (with the upper case D) and everything works!  So the problem is allowing fish to fuzzy match the Development as development  because it used what you typed as the pwd.  But if you run fish again, it recalculates the value of pwd and uses the actual path (with upper case D).
![image](https://user-images.githubusercontent.com/2267531/52873223-7eefc980-311c-11e9-8c67-963abf1f7103.png)

**Comment by JanStevens** [comment] 2019-03-13 10:49
Hello,

I seem to have the same issue, on some git repo's it works, on other it doesn't

Works on master and bobthefish git repo
![Screenshot 2019-03-13 at 11 47 20](https://user-images.githubusercontent.com/1540483/54273281-dfd8b900-4585-11e9-9328-c563bb20cb18.png)

Does not work on any other project in that dir
![Screenshot 2019-03-13 at 11 47 46](https://user-images.githubusercontent.com/1540483/54273280-dfd8b900-4585-11e9-9bb1-fd8760c60b2b.png)

**Closed** 2019-03-18 14:44 UTC

**Comment by bobthecow** [comment] 2019-03-18 14:46
All permutations of this should now be resolved. Feel free to re-open if you run into it again :)
