### ISSUE TITLE
`cd /` hangs.

### ISSUE THREAD

**Issue by Dietr1ch** [oh-my-fish/theme-bobthefish#127] opened 2018-01-28 06:58 UTC
It gets into a loop and grabs a core at 100%.
I'm glad we are on a multi-core world now, that used to mean a hard restart or a painfully slow kill.

**Comment by bobthecow** [comment] 2018-01-28 08:34
I'm not able to reproduce this. Do you have a git or hg repo at root for some reason?

**Comment by Dietr1ch** [comment] 2018-01-28 09:20
I do have a git repo at `~` but I have one at `/`, although starting from a non git/hg repo directory didn't helped, `cd /tmp;  and  cd /` still hangs.

I checked fisherman's repo and it's at the current master, `728c52d`

This is the loop I see when using `fish -d 3`,

    <3> fish: proc::read_try('[ -e $d/.hg ]')
    <3> fish: Skipping fork: buffered output for internal builtin 'string'
    <3> fish: Set status of string replace -r '/[^/]+/?$' '' -- $argv to 1 using short circuit
    <3> fish: Job is constructed
    <3> fish: proc::read_try('string replace -r '/[^/]+/?$' '' -- $argv')
    <3> fish: Job is constructed
    <3> fish: proc::read_try('__bobthefish_dirname $d')
    <3> fish: Skipping fork: no output for internal builtin 'set'
    <3> fish: Set status of set d (__bobthefish_dirname $d) to 1 using short circuit
    <3> fish: Job is constructed
    <3> fish: proc::read_try('set d (__bobthefish_dirname $d)')
    <3> fish: Skipping fork: no output for internal builtin '['
    <3> fish: Set status of not [ -z "$d" ] to 1 using short circuit
    <3> fish: Job is constructed
    <3> fish: proc::read_try('not [ -z "$d" ]')
    <3> fish: Skipping fork: no output for internal builtin '['
    <3> fish: Set status of [ -e $d/.hg ] to 1 using short circuit
    <3> fish: Job is constructed
    <3> fish: proc::read_try('[ -e $d/.hg ]')

**Comment by bobthecow** [comment] 2018-01-29 03:45
ooh. got it.

**Comment by bobthecow** [comment] 2018-01-29 03:46
Okay. Update your theme, and it should be fixed. Let me know if you're still seeing issues!

**Closed by bobthecow** 2018-01-29 03:46 UTC

**Comment by Dietr1ch** [comment] 2018-01-29 03:55
Thanks for the quick fix!

**Comment by bobthecow** [comment] 2018-01-29 04:19
No problem. Happy to help.
